# E2E tests with LocalStack
name: E2E Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e-tests:
    name: E2E Tests with LocalStack
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.10.*'
          - '1.11.*'
          - '1.12.*'
          - '1.13.*'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@9392b05ddb345894c2e86305fc426566e738c1db # v0.2.4
        with:
          image-tag: 'latest'
          install-awslocal: 'true'
          configuration: SERVICES=ssm,sts DEBUG=1
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
      
      - name: Verify LocalStack SSM service
        run: |
          echo "Testing LocalStack SSM service..."
          awslocal ssm put-parameter \
            --name "/test/connectivity" \
            --value "test" \
            --type "String" \
            || { echo "Failed to connect to LocalStack SSM"; exit 1; }
          echo "LocalStack SSM is working!"
      
      - name: Download Go dependencies
        run: go mod download
      
      - name: Build provider
        run: |
          go build -o terraform-provider-fastssm
          chmod +x terraform-provider-fastssm
      
      - name: Install provider locally
        run: |
          PLUGIN_DIR="$HOME/.local/share/terraform/plugins"
          mkdir -p "$PLUGIN_DIR"
          cp terraform-provider-fastssm "$PLUGIN_DIR/"
          echo "Provider installed to: $PLUGIN_DIR"
          ls -lh "$PLUGIN_DIR"
          echo "Verifying provider binary:"
          file "$PLUGIN_DIR/terraform-provider-fastssm"
          "$PLUGIN_DIR/terraform-provider-fastssm" --version || echo "Version check failed, but binary exists"
      
      - name: Run E2E tests
        run: |
          cd tests/e2e
          bash run-e2e-tests.sh
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
          TF_LOG: DEBUG
          CHECKPOINT_DISABLE: 1
      
      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: e2e-test-artifacts-tf-${{ matrix.terraform }}
          path: |
            tests/e2e/*.tfstate
            tests/e2e/*.log
            tests/e2e/output.json
          retention-days: 7

